spring:
  datasource:
    url: jdbc:mysql://localhost:3306/hospital_xs
#    url: jdbc:mysql://mysql.4kb.cn:25287/hospital_xs
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
mybatis:
  type-aliases-package: com.caihao.hospitalmanager.entity
  mapper-locations: classpath:mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
pagehelper:
    helperDialect: mysql
    reasonable: true
    supportMethodsArguments: true
    params: count=countSql
server:
  port: 8080